# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='email',
            field=models.CharField(max_length=32, verbose_name='邮件地址'),
        ),
    ]
