# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcs', '0002_auto_20180617_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='email',
            field=models.CharField(max_length=100, verbose_name='邮件地址'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='letter',
            field=models.CharField(max_length=100, verbose_name='IDC简称'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=100, verbose_name='机房名称'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='联系人'),
        ),
    ]
